name: Deploy to EC2

on:
  push:
      branches:
        - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: zip
        run: zip -r deploy.zip . -x '.git*' -x 'node_modules/*'

      - name: upload to S3
        run: |
          aws s3 cp deploy.zip s3://nextjs-deploy-artifacts-513148686116/deploy.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1

      - name: deploy via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name nextjs-app \
            --deployment-group-name nextjs-deloyment-group \
            --s3-location bucket-nextjs-deploy-artifacts-513148686116,key=deploy.zip,bundleType=zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
